image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 12 x64
  - npm install

build_script:
  - npm run dist

deploy:
  release: SecurVid Desktop-v$(APPVEYOR_BUILD_VERSION)
  description: 'SecurVid Desktop'
  provider: GitHub
  auth_token:
    secure: n9kYuqSKDc2gg0llXCutxXnc2XvYpVXIm2oLdWNQvImPfnzx7umWskeUcm7uYzBU # your encrypted token from GitHub
 # artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
   # APPVEYOR_REPO_TAG: true        # deploy on tag push only
