name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: sudo apt-get install libx11-dev zlib1g-dev libpng-dev libxtst-dev
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
  build-mac:
    name: macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Fixup Xcode
      # https://github.com/actions/virtual-environments/issues/2557
      run: |
        sudo xcode-select -s "/Applications/Xcode_12.4.app"
        sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
    - name: Prepare for app notarization
      # Import Apple API key for app notarization on macOS
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_LINK: ${{ secrets.mac_certs }}
        CSC_KEY_PASSWORD: ${{ secrets.mac_certs_password }}
        API_KEY_ID: ${{ secrets.api_key_id }}
        API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
      run: |
        npm install
        npm run lint
        npm run dist
  build-windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
